version: "3.7"

services:
  web:
    build: app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB=${DB}
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB}'
